/// Generated by AssetsRefGenerator on 2023/02/04
class Res {
  static const String cat_551554__480 = "asset/cat-551554__480.jpg";
  static const String catpng = "asset/catpng.jpg";
  static const String catpng2 = "asset/catpng2.jpg";
  static const String catpng3 = "asset/catpng3.jpg";
  static const String cats1 = "asset/cats1.jpeg";
  static const String cats2 = "asset/cats2.jpeg";
  static const String cats3 = "asset/cats3.jpeg";
  static const String catspng5 = "asset/catspng5.jpg";
  static const String dog11 = "asset/dog11.webp";
  static const String dog2 = "asset/dog2.webp";
  static const String dog3 = "asset/dog3.jpeg";
  static const String download = "asset/download.jpg";
  static const String images11122 = "asset/images11122.png";
  static const String images12334 = "asset/images12334.png";
  static const String profilepic = "asset/profilepic.webp";
}
